services:
  backend:
    build: .
    container_name: mera_paisa
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/personal_finance_db
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - personal_finance_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_BACKEND_URL: http://backend:8000
    container_name: personal_finance_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - SKIP_TYPE_CHECK=true
    ports:
      - "3000:3000"
    networks:
      - personal_finance_network

networks:
  personal_finance_network:
    external: true
